# Generated by Django 5.0.6 on 2024-08-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limte_gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_economia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
