# Generated by Django 5.0.6 on 2024-08-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_movimentacao_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='categoria',
            field=models.CharField(choices=[('Transporte', 'Transporte'), ('Comida', 'Comida'), ('Roupas', 'Roupas'), ('Lazer', 'Lazer'), ('Outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
