# Generated by Django 5.0.6 on 2024-08-26 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_limte_gastos_orcamento_limite_gastos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='orcamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.orcamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida')], default='Entrada', max_length=10),
            preserve_default=False,
        ),
    ]
