# Generated by Django 5.0.6 on 2024-08-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_movimentacao_orcamento_movimentacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='mensagem',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
