# Generated by Django 5.0.6 on 2024-09-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_movimentacao_data_movimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='mensagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
