# Generated by Django 5.0.6 on 2024-09-11 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_movimentacao_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='proxima_movimentacao',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
